Float32 support
KNX-IOT/KNX-IOT-STACK pull request #683
Opened 2023-07-21 13:04 UTC by tiniuclx

2023-07-21 13:15 UTC, tiniuclx commented
~format

2023-07-21 13:30 UTC, Skyler84 commented on include/oc_rep.h
>  } oc_rep_value_type_t;
There were some usages of OC_REP_ARRAY | OC_REP_XXX to represent array types previously, this could break if OC_REP_ARRAY isn't kept as a bitmask of sorts. https://github.com/KNX-IOT/KNX-IOT-STACK/blob/8ccc6cc0fa208cd972428793180f06000b6487b9/api/oc_rep.c#L355

2023-07-21 13:38 UTC, Skyler84 approved these changes

2023-07-24 08:44 UTC, WAvdBeek requested changes
we need additional tests for this change

2023-07-24 12:59 UTC, tiniuclx commented
~format

2023-07-24 13:04 UTC, tiniuclx commented
Added tests for the float functions & fixed a memory allocation issue to do with float arrays. Should be good to go!

2023-07-24 14:57 UTC, WAvdBeek approved these changes

2023-07-24 14:57 UTC, merged