EITT fixes
KNX-IOT/KNX-IOT-STACK pull request #753
Opened 2024-01-02 14:31 UTC by FrankZRS

1. Set default sna & da to 255 according to Spec Table 16

2024-01-03 14:38 UTC, FrankZRS commented
~format

2024-01-05 09:21 UTC, WAvdBeek commented on api/oc_knx.c
> -#ifdef OC_USE_MULTICAST_SCOPE_2
we still need to send the multicast scope 2 for windows only

2024-01-05 09:23 UTC, WAvdBeek commented on api/oc_knx_dev.c
> -    uint8_t sa = (uint8_t)((device->ia) >> 8);
this value needs to come from somewhere, e.g. can't be fixed 255..

2024-01-05 09:26 UTC, WAvdBeek requested changes

2024-01-05 09:26 UTC, WAvdBeek commented on api/oc_knx_dev.c
> -    uint8_t da = (uint8_t)(device->ia);
same here.

2024-01-05 11:02 UTC, FrankZRS commented
~format

2024-01-05 12:11 UTC, merged