Frank eitt fix
KNX-IOT/KNX-IOT-STACK pull request #771
Opened 2024-02-23 14:37 UTC by FrankZRS

2024-02-27 11:32 UTC, WAvdBeek requested changes

2024-02-27 11:32 UTC, WAvdBeek commented on api/oc_knx_sec.c
> +                PRINT("   if.ll is not a valid access scope!\n");
can we do this as a debug statement (OC_DEBUG)?

2024-02-27 11:32 UTC, WAvdBeek commented on api/oc_knx_client.c
> +        PRINT("      ga : %lu\n", group_address);
OC_DEBUG?

2024-02-27 11:32 UTC, WAvdBeek commented on api/oc_knx_sec.c
> +                PRINT("   if.ll is not a valid access scope!\n");
OC_DBG

2024-02-27 12:11 UTC, FrankZRS commented on api/oc_knx_client.c
> +        PRINT("      ga : %lu\n", group_address);
This was a PRINT before, I just fixed the format identifier. There's quite a few more PRINT's in this function, do you want me to change them all?

2024-02-27 12:12 UTC, FrankZRS commented on api/oc_knx_sec.c
> +                PRINT("   if.ll is not a valid access scope!\n");
Fixed. I used OC_ERR since it's an error that's leading to a BAD_REQUEST response

2024-02-27 12:12 UTC, FrankZRS commented
~format

2024-03-04 10:29 UTC, WAvdBeek commented
~format

2024-03-04 10:34 UTC, merged